# Generated by Django 4.0.6 on 2022-07-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('rut', models.IntegerField(null=True)),
                ('edad', models.IntegerField(null=True)),
                ('comuna', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('nombre_v', models.CharField(max_length=10, verbose_name='Vacuna')),
                ('nro_dosis', models.IntegerField(verbose_name='Numero dosis')),
                ('tfno', models.IntegerField(verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('Contraseña', models.CharField(max_length=30)),
                ('Contraseña2', models.CharField(default='Some String', max_length=30)),
                ('Tipo_u', models.CharField(max_length=30)),
            ],
        ),
    ]
