# Generated by Django 4.0.6 on 2022-07-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Tipo_u',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
