# Generated by Django 2.2.3 on 2022-07-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_personas', '0003_auto_20220712_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Contraseña',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Contraseña2',
            field=models.IntegerField(default='Some String'),
        ),
    ]
