# Generated by Django 2.2.3 on 2022-07-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos_personas', '0004_auto_20220712_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Contraseña',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Contraseña2',
            field=models.CharField(default='Some String', max_length=30),
        ),
    ]
